name: "dbt prd pipeline"

# Triggers
on:
  # Triggers the workflow on push to main branch
  push:
	branches : [main]
 
jobs:
  # Build job
  testing:
	runs-on: ubuntu-latest
	steps:
		- run : |
			echo "This works for u"

