name: "dbt testing"

# Triggers
on:
  # Triggers the workflow on push to main branch  fdsfdsf
  push:
   branches:
    - main

jobs:
  # Build job
  testing_1:
   runs-on: self-hosted
   env:
    ENV_CODE: ${{vars.ENV_CODE}}
    PROJ_CODE: ${{vars.PROJ_CODE}}
   steps:
     - run : echo "This works for u only not any more"
     - name: "Step 01 - Checkout current branch"
       id: step-01
       uses: actions/checkout@v3
     - name: "Step 02 - Install dbt"
       id: step-02
       run: pip3 install dbt-core dbt-sqlserver
     - name: "Step 03 - Verify dbt"
       id: step-03
       run: dbt --version
     - name: "Step 04 - Compile dbt"
       id: step-04
       working-directory: ./dbt-docs/dbt
       run: |
        ls -ltra
        export DBT_PROFILES_DIR=$PWD
        dbt deps
        dbt debug -t $ENV_CODE
        dbt compile -t $ENV_CODE
