name: "dbt prd pipeline"

# Triggers
on:
  # Triggers the workflow on push to main branch  fdsfdsf
  push:
   branches:
    - main

jobs:
  # Build job
  testing_1:
   runs-on: self-hosted
   steps:
     - run : echo "This works for u only not any more"
