name: "dbt prd pipeline Full"

# Triggers
on:
  # Triggers the workflow on push to main branch    
  push:
   branches:
   - main
  # Triggers the workflow manually from GUI
# workflow_dispatch:

jobs:
  # Build job
    build:
        runs-on: self-hosted
        environment: dev
        env:
            ENV_CODE: ${{vars.ENV_CODE}}
            PROJ_CODE: ${{vars.PROJ_CODE}}
        steps:
            - name: "Print a greeting"
 
